config/routes.rb
Mywiki::Application.routes.draw do

  devise_for :users
  resources :wikis
  resources :charges, only: [:new, :create]
  root :to => 'static_pages#home'

  
  

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :confirmed_at, :premium
  

  #Relationships
  has_many :wikis

  def is_premium?
    self.premium
  end
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  attr_accessible :title, :content, :user_id, :last_edited_by, :updated_at

  #Validations
  validates_presence_of :title, :content, :user_id

  #Relationships
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_filter :authenticate_user!

  def new
   @stripe_btn_data = {
     key: "#{ Rails.configuration.stripe[:publishable_key] }",
     description: "MyWiki Premium Upgrade",
     amount: 5_99
   }
  end

  def create
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )
   
    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: 5_99,
      description: "MyWiki Membership",
      currency: 'usd'
    )

    current_user.premium = true
    current_user.save
    flash[:success] = "Thank you for your payment you are now a premium user"
    redirect_to root_path

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to charges_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
	end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_filter :set_wiki, only: [:show, :edit, :update, :destroy]
  before_filter :authorize_user, only: [:destroy]
  before_filter :authenticate_user!, except: [:index, :show]
  
  respond_to :html, :xml, :json, :js

  def index
    @wikis = Wiki.all
    respond_with(@wikis)
  end

  def show
    respond_with(@wiki)
  end

  def new
    @wiki = Wiki.new
    respond_with(@wiki)
  end

  def edit
  end

  def create
    @wiki = Wiki.new(params[:wiki])
    @wiki.user = current_user
    @wiki.save
    respond_with(@wiki)
  end

  def update
    params[:wiki].merge!(last_edited_by: current_user.email)
    @wiki.update_attributes(params[:wiki])
    respond_with(@wiki)
  end

  def destroy
    @wiki.destroy
    respond_with(@wiki)
  end

  private
    def set_wiki
      @wiki = Wiki.find(params[:id])
    end

    def authorize_user
      set_wiki
      if @wiki.user != current_user
        redirect_to wikis_path, notice: "You can only delete wikis you have created. :("
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/wiki_helper.rb
module WikiHelper
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
   <h3>Upgrade to get unlimited private Wikis</h3>
   <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" 
    data-key="<%= @stripe_btn_data[:key] %>"
    data-email="<%= current_user.email %>" 
    data-amount="<%= @stripe_btn_data[:amount] %>"
    data-description="<%= @stripe_btn_data[:description] %>" >
   </script>
 <% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
      <ul class='no-bullet'>
        <li>
          <%= value %>
        </li>
      </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mywiki</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href='/'>MyWiki</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class='nav navbar-nav'>
        <li><%= link_to("Wikis", wikis_path) %>
            <% if current_user %>
              <li>
                <% if current_user.is_premium? == false %>
                  <%= link_to("Upgrade to Premium", new_charge_path) %>
                <% else %>
                  <a href='#'>Create new private wiki</a>
                <% end %></li>
                <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
              </li>
            <% else %>
              <li>
                <%= link_to('Login', new_user_session_path)  %>  
              </li>
            <% end %>
          </ul>
      </div>
  </div>
</nav>
  <div class='container'>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </div>
</body>
</html>

app/views/static_pages/home.html.erb
<div class='index row'>
<h1>Welcome to MyWiki!</h1>
<%= link_to "See Wikis", wikis_path, class: 'btn btn-default' %>
</div>

app/views/wikis/_form.html.erb
<%= form_for(@wiki) do |f| %>
  <%= f.label :title %><br />
  <%= f.text_field :title %><br />
  <%= f.label :content %><br />
  <%= f.text_area :content %><br />
  <%= f.submit "Save Wiki" %>
<% end %>

app/views/wikis/_wiki.html.erb
<h2><%= @wiki.title %></h2>
<p>
  <small><strong>Created by:</strong> 
    <%= @wiki.user.email %> about <%= time_ago_in_words(@wiki.created_at) %> ago.
  <% if @wiki.last_edited_by %>
    <br />
    <strong>Last updated by:</strong> 
    <%= @wiki.last_edited_by %> about <%= time_ago_in_words(@wiki.updated_at) %> ago. 
  <% end %>
  </small>
</p>
<p>
  <%= @wiki.content %> 
  <% if @wiki.user == current_user %>
    - 
    <%= link_to 'Destroy wiki?', @wiki, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</p>

<% if current_user %>
  <%= link_to 'Edit wiki', edit_wiki_path(@wiki) %>
<% end %>
<br />
<%= link_to 'Back to all wikis', wikis_path %>

app/views/wikis/edit.html.erb
<h2>Edit Wiki</h2>
<%= render 'form' %>

app/views/wikis/index.html.erb
<h2>Wikis</h2>
<h4><%= link_to("Create new wiki", new_wiki_path) %></h4>

<% @wikis.each do |wiki| %>
  <h3><%= link_to wiki.title, wiki %></h3>
  <p>
    <small><strong>Created by:</strong> 
      <%= wiki.user.email %> about <%= time_ago_in_words(wiki.created_at) %> ago.
    <% if wiki.last_edited_by %>
      <br />
      <strong>Last updated by:</strong> 
      <%= wiki.last_edited_by %> about <%= time_ago_in_words(wiki.updated_at) %> ago. 
    <% end %>
    </small>
  </p>
  <p>
    <%= wiki.content %> 
    <% if wiki.user == current_user %>
      - 
      <%= link_to 'Destroy Wiki?', wiki, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </p>
<% end %>

app/views/wikis/new.html.erb
<h1>Create New Wiki</h1>

<%= render 'form' %>

app/views/wikis/show.html.erb
<%= render 'wiki' %>